version: '3'

services:
  database:
    image: "bitnami/postgresql:10.15.0-debian-10-r54"
    env_file:
      - database.env # configure postgres
    ports:
      - "5431:5432"
    volumes:
      - ./pg_hba.conf:/bitnami/postgresql/conf/pg_hba.conf
    networks:
      - app-network

  web:
    build: .
    command: bin/recom
    ports:
      - "3456:3456"
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
